# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
workspace 'iOS Test Runner'

target 'iOS Test Runner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Test Runner
  pod 'BoringSSL'
end
